#!/bin/bash
#
# Functions
ip="$1"
domain="$2"
subdomains="$3"

mode="appened"
mode_simbol="+"


function append {
	# domains
	if [ -z $domain ];then
		echo "Usage: $0 IP DOMAIN [subdomain[,subdomain]] [-d | -a]" >&2
		exit 1
	fi

	echo -e "$ip\t$domain" | tee -a /etc/hosts > /dev/null 2>&1
	# subdomains
	if [ -n $subdomains ];then
		while read subdomain; do 
			echo -e "$ip\t$subdomain.$domain" | tee -a /etc/hosts > /dev/null 2>&1 
		done <<< $(echo "$subdomains" | tr ',' '\n')
	fi
}


function draw_modifications {
	# Write in /etc/hosts
	echo "MODE: $mode" 
	# SDL
	echo -e "\nSDL.TDL"
	echo -e "\t[$mode_simbol] $ip\t$domain\n"
	# Subdomains
	if [ -n $subdomains ];then
		echo -e "\nSubdomains"
		while read subdomain; do 
			echo -e "\t[$mode_simbol] $ip\t$subdomain.$domain "
		done <<< $(echo "$subdomains" | tr ',' '\n')
	fi
}
# Arguments verifications
if [ $# -eq 0 ];then
	echo "Usage: $0 IP DOMAIN [subdomain[,subdomain]] [-d | -a]" >&2
	exit 1
fi
# Main
echo $* | grep -o '\-.'
if [ $(echo $?) -eq 0 ];then
	option=$(echo $* | grep -o '\-.' | tr -d '\-')
	case $option in
		d)
		mode="delete"
		mode_simbol="-"
		sed -i "/$ip/,/$domain/d" /etc/hosts
		draw_modifications
		exit 0
		;;
			
		a)
		mode="appened"
		mode_simbol="+"
		append
		draw_modifications
		;;

		*)
		echo "Usage: $0 IP DOMAIN [subdomain[,subdomain]] [-d | -a]" >&2
		;;
	esac
else
	append
	draw_modifications
fi

